module:
  imports: 
    # Add the Wowchemy CMS module below, if it has not already been added:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5

